"""add arxiv paper table

Revision ID: 8bdaab87d45c
Revises: ffd4d2ed95e3
Create Date: 2021-04-23 11:15:33.760232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdaab87d45c'
down_revision = 'ffd4d2ed95e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subjects', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arxiv_paper')
    # ### end Alembic commands ###
