"""initial revision

Revision ID: ffd4d2ed95e3
Revises:
Create Date: 2021-03-26 23:50:28.608567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffd4d2ed95e3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mathematician",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("school", sa.String(), nullable=True),
        sa.Column("graduated", sa.String(), nullable=True),
        sa.Column("thesis", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("math_genealogy_url", sa.String(), nullable=True),
        sa.Column("math_sci_net_url", sa.String(), nullable=True),
        sa.Column("publications", sa.Integer(), nullable=True),
        sa.Column("citations", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "student_advisor",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("advisor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisor_id"],
            ["mathematician.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["mathematician.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_advisor")
    op.drop_table("mathematician")
    # ### end Alembic commands ###
